"""Added bridge table: time_table_standard.

Revision ID: 3fbe8fbef158
Revises: c915de520d6d
Create Date: 2024-08-19 14:54:48.271499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbe8fbef158'
down_revision: Union[str, None] = 'c915de520d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_time_table_standard',
    sa.Column('bridge_time_table_standard', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('foreign_key_hash', sa.BIGINT(), nullable=False),
    sa.Column('attribute_hash', sa.BIGINT(), nullable=False),
    sa.Column('period_ending_key', sa.Integer(), nullable=True, redshift_distkey='period_ending_key'),
    sa.Column('duration_key', sa.Integer(), nullable=True),
    sa.Column('annum_key', sa.Integer(), nullable=True),
    sa.Column('start_date_key', sa.Integer(), nullable=True),
    sa.Column('end_date_key', sa.Integer(), nullable=True),
    sa.Column('weighted_business_days', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['annum_key'], ['finance_dw.dim_annum.annum_key'], ),
    sa.ForeignKeyConstraint(['duration_key'], ['finance_dw.dim_duration.duration_key'], ),
    sa.ForeignKeyConstraint(['end_date_key'], ['finance_dw.dim_calendar.date_key'], ),
    sa.ForeignKeyConstraint(['period_ending_key'], ['finance_dw.dim_calendar.date_key'], ),
    sa.ForeignKeyConstraint(['start_date_key'], ['finance_dw.dim_calendar.date_key'], ),
    sa.PrimaryKeyConstraint('bridge_time_table_standard'),
    sa.UniqueConstraint('period_ending_key', 'duration_key', 'annum_key'),
    schema='finance_dw'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bridge_time_table_standard', schema='finance_dw')
    # ### end Alembic commands ###
