"""Added bridge_time_table_comp

Revision ID: 59a5b26c79cf
Revises: d3484598c542
Create Date: 2024-09-20 11:34:29.209566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a5b26c79cf'
down_revision: Union[str, None] = 'd3484598c542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_time_table_comp',
    sa.Column('bridge_time_table_comp', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('foreign_key_hash', sa.BIGINT(), nullable=False),
    sa.Column('attribute_hash', sa.BIGINT(), nullable=False),
    sa.Column('branch_key', sa.Integer(), nullable=True),
    sa.Column('period_ending_key', sa.Integer(), nullable=True),
    sa.Column('duration_key', sa.Integer(), nullable=True),
    sa.Column('annum_key', sa.Integer(), nullable=True),
    sa.Column('start_date_key', sa.Integer(), nullable=True),
    sa.Column('end_date_key', sa.Integer(), nullable=True),
    sa.Column('weighted_business_days', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('bridge_time_table_comp'),
    sa.UniqueConstraint('branch_key', 'period_ending_key', 'duration_key', 'annum_key'),
    schema='finance_dw',
    redshift_interleaved_sortkey=('branch_key', 'period_ending_key', 'duration_key', 'annum_key')
    )
    op.create_table('bridge_time_table_comp_source',
    sa.Column('bridge_time_table_comp', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('foreign_key_hash', sa.BIGINT(), nullable=False),
    sa.Column('attribute_hash', sa.BIGINT(), nullable=False),
    sa.Column('branch_key', sa.Integer(), nullable=True),
    sa.Column('period_ending_key', sa.Integer(), nullable=True),
    sa.Column('duration_key', sa.Integer(), nullable=True),
    sa.Column('annum_key', sa.Integer(), nullable=True),
    sa.Column('start_date_key', sa.Integer(), nullable=True),
    sa.Column('end_date_key', sa.Integer(), nullable=True),
    sa.Column('weighted_business_days', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('action', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('bridge_time_table_comp'),
    schema='finance_etl'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bridge_time_table_comp_source', schema='finance_etl')
    op.drop_table('bridge_time_table_comp', schema='finance_dw')
    # ### end Alembic commands ###
