"""Added DimPart

Revision ID: 75c605aebcdc
Revises: c63c61a485d5
Create Date: 2024-09-12 09:57:13.627743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c605aebcdc'
down_revision: Union[str, None] = 'c63c61a485d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_part',
    sa.Column('part_id_key', sa.Integer(), nullable=False),
    sa.Column('foreign_key_hash', sa.BIGINT(), nullable=False),
    sa.Column('attribute_hash', sa.BIGINT(), nullable=False),
    sa.Column('sku', sa.Numeric(precision=22, scale=0), nullable=True),
    sa.Column('part_id', sa.String(length=24), nullable=True),
    sa.Column('part_id_2', sa.String(length=24), nullable=True),
    sa.Column('product_line', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('part_description', sa.String(length=400), nullable=True),
    sa.Column('part_description_specific', sa.String(length=160), nullable=True),
    sa.Column('part_category', sa.String(length=60), nullable=True),
    sa.Column('part_subcategory', sa.String(length=60), nullable=True),
    sa.Column('part_segment', sa.String(length=60), nullable=True),
    sa.Column('popularity', sa.String(length=4), nullable=True),
    sa.Column('master_installer_flag', sa.Integer(), nullable=True),
    sa.Column('active', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('part_id_key'),
    schema='finance_dw',
    redshift_distkey='part_id_key',
    redshift_diststyle='KEY',
    redshift_interleaved_sortkey=('part_id', 'product_line', 'part_category', 'part_subcategory', 'part_segment')
    )
    op.create_table('dim_part_source',
    sa.Column('part_id_key', sa.Integer(), nullable=False),
    sa.Column('foreign_key_hash', sa.BIGINT(), nullable=False),
    sa.Column('attribute_hash', sa.BIGINT(), nullable=False),
    sa.Column('sku', sa.Numeric(precision=22, scale=0), nullable=True),
    sa.Column('part_id', sa.String(length=24), nullable=True),
    sa.Column('part_id_2', sa.String(length=24), nullable=True),
    sa.Column('product_line', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('part_description', sa.String(length=400), nullable=True),
    sa.Column('part_description_specific', sa.String(length=160), nullable=True),
    sa.Column('part_category', sa.String(length=60), nullable=True),
    sa.Column('part_subcategory', sa.String(length=60), nullable=True),
    sa.Column('part_segment', sa.String(length=60), nullable=True),
    sa.Column('popularity', sa.String(length=4), nullable=True),
    sa.Column('master_installer_flag', sa.Integer(), nullable=True),
    sa.Column('active', sa.String(length=6), nullable=True),
    sa.Column('action', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('part_id_key'),
    schema='finance_etl'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_part_source', schema='finance_etl')
    op.drop_table('dim_part', schema='finance_dw')
    # ### end Alembic commands ###
