"""Added tables to metadata schema.

Revision ID: 7f42731d0ae9
Revises: e199de86f77e
Create Date: 2024-09-03 14:57:40.060743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f42731d0ae9'
down_revision: Union[str, None] = 'e199de86f77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_source_import_bea',
    sa.Column('id', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('source', sa.String(length=10), nullable=True, redshift_sortkey=True),
    sa.Column('series_type', sa.String(length=20), nullable=True),
    sa.Column('series_id', sa.String(length=20), nullable=True),
    sa.Column('series_title', sa.String(length=255), nullable=True),
    sa.Column('series_short_title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_meta'
    )
    op.create_table('metadata_source_import_bls',
    sa.Column('id', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('source', sa.String(length=10), nullable=True, redshift_sortkey=True),
    sa.Column('series_type', sa.String(length=20), nullable=True),
    sa.Column('series_id', sa.String(length=20), nullable=True),
    sa.Column('series_title', sa.String(length=255), nullable=True),
    sa.Column('series_short_title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_meta'
    )
    op.create_table('metadata_source_import_flat_files',
    sa.Column('id', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('source_location', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('target_server', sa.String(length=50), nullable=True),
    sa.Column('target_database', sa.String(length=30), nullable=True),
    sa.Column('target_schema', sa.String(length=50), nullable=True),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('sql_target_select_statement', sa.String(), nullable=True),
    sa.Column('sql_target_create_statement', sa.String(), nullable=True),
    sa.Column('sql_target_truncate_statement', sa.String(), nullable=True),
    sa.Column('sql_target_drop_statement', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_meta'
    )
    op.create_table('metadata_source_import_fred',
    sa.Column('id', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('source', sa.String(length=10), nullable=True, redshift_sortkey=True),
    sa.Column('series_type', sa.String(length=20), nullable=True),
    sa.Column('series_id', sa.String(length=20), nullable=True),
    sa.Column('series_title', sa.String(length=255), nullable=True),
    sa.Column('series_short_title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_meta'
    )
    op.create_table('metadata_source_import_iseries',
    sa.Column('id', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('source_schema', sa.String(length=50), nullable=True),
    sa.Column('source_table', sa.String(length=50), nullable=True),
    sa.Column('source_table_description', sa.String(length=100), nullable=True),
    sa.Column('target_server', sa.String(length=30), nullable=True),
    sa.Column('target_database', sa.String(length=30), nullable=True),
    sa.Column('target_schema', sa.String(length=50), nullable=True),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('sql_source_select_statement', sa.String(), nullable=True),
    sa.Column('sql_target_select_statement', sa.String(), nullable=True),
    sa.Column('sql_target_create_statement', sa.String(), nullable=True),
    sa.Column('sql_target_truncate_statement', sa.String(), nullable=True),
    sa.Column('sql_target_drop_statement', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_meta'
    )
    op.create_table('metadata_source_import_iseries_gl',
    sa.Column('id', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('source_schema', sa.String(length=50), nullable=True),
    sa.Column('source_table', sa.String(length=50), nullable=True),
    sa.Column('source_table_description', sa.String(length=100), nullable=True),
    sa.Column('target_server', sa.String(length=30), nullable=True),
    sa.Column('target_database', sa.String(length=30), nullable=True),
    sa.Column('target_schema', sa.String(length=50), nullable=True),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('sql_source_select_statement', sa.String(), nullable=True),
    sa.Column('sql_target_select_statement', sa.String(), nullable=True),
    sa.Column('sql_target_create_statement', sa.String(), nullable=True),
    sa.Column('sql_target_truncate_statement', sa.String(), nullable=True),
    sa.Column('sql_target_drop_statement', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_meta'
    )
    op.create_table('metadata_source_import_iseries_mhf',
    sa.Column('id', sa.Integer(), nullable=False, redshift_identity=(1, 1)),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('source_schema', sa.String(length=50), nullable=True),
    sa.Column('source_table', sa.String(length=50), nullable=True),
    sa.Column('source_table_description', sa.String(length=100), nullable=True),
    sa.Column('target_server', sa.String(length=30), nullable=True),
    sa.Column('target_database', sa.String(length=30), nullable=True),
    sa.Column('target_schema', sa.String(length=50), nullable=True),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('sql_source_select_statement', sa.String(), nullable=True),
    sa.Column('sql_target_select_statement', sa.String(), nullable=True),
    sa.Column('sql_target_create_statement', sa.String(), nullable=True),
    sa.Column('sql_target_truncate_statement', sa.String(), nullable=True),
    sa.Column('sql_target_drop_statement', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance_meta'
    )
    op.drop_table('dw_meta_bridges', schema='finance_meta')
    op.drop_table('meta_source_to_target_tables', schema='finance_meta')
    op.drop_table('dw_meta_dimensions', schema='finance_meta')
    op.drop_table('metadata_statistical_import', schema='finance_meta')
    op.drop_table('meta_source_to_target_columns', schema='finance_meta')
    op.drop_table('dw_meta_facts', schema='finance_meta')
    op.drop_table('dw_meta_tables', schema='finance_meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dw_meta_tables',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('"identity"(443318, 0, \'1,1\'::text)'), autoincrement=False, nullable=False),
    sa.Column('database_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('schema_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('table_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('unique_columns', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('source_query', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dw_meta_tables_pkey'),
    schema='finance_meta',
    redshift_distkey=None,
    redshift_diststyle=None,
    redshift_interleaved_sortkey=None,
    redshift_sortkey=()
    )
    op.create_table('dw_meta_facts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('"identity"(443333, 0, \'1,1\'::text)'), autoincrement=False, nullable=False),
    sa.Column('database_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('schema_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('column_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('ordinal_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('column_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('column_default', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('is_nullable', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('character_maximum_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeric_precision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeric_scale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('is_primary_key', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auto_increment', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('foreign_key_table', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('foreign_key_column', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('unique_constraint', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dw_meta_facts_pkey'),
    schema='finance_meta',
    redshift_distkey=None,
    redshift_diststyle=None,
    redshift_interleaved_sortkey=None,
    redshift_sortkey=()
    )
    op.create_table('meta_source_to_target_columns',
    sa.Column('target_server', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_database', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_schema', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_table', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_column', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_column_heading', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_column', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_column_data_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_column_data_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('primary_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.INTEGER(), autoincrement=False, nullable=True),
    schema='finance_meta',
    redshift_distkey=None,
    redshift_diststyle=None,
    redshift_interleaved_sortkey=None,
    redshift_sortkey=()
    )
    op.create_table('metadata_statistical_import',
    sa.Column('source', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('series_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('series_id', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('series_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('series_short_title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    schema='finance_meta',
    redshift_distkey=None,
    redshift_diststyle=None,
    redshift_interleaved_sortkey=None,
    redshift_sortkey=()
    )
    op.create_table('dw_meta_dimensions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('"identity"(443323, 0, \'1,1\'::text)'), autoincrement=False, nullable=False),
    sa.Column('database_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('schema_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('column_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('ordinal_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('column_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('column_default', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('is_nullable', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('character_maximum_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeric_precision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeric_scale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('is_primary_key', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auto_increment', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('foreign_key_table', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('foreign_key_column', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('unique_constraint', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dw_meta_dimensions_pkey'),
    schema='finance_meta',
    redshift_distkey=None,
    redshift_diststyle=None,
    redshift_interleaved_sortkey=None,
    redshift_sortkey=()
    )
    op.create_table('meta_source_to_target_tables',
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('source_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_schema', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_table', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_tab', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_server', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_database', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_schema', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_table', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('daily_upload', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monthly_upload', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_filter', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sql_source_select_statement', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('sql_target_select_statement', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('sql_target_create_statement', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('sql_target_truncate_statement', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    sa.Column('sql_target_drop_statement', sa.VARCHAR(length=65535), autoincrement=False, nullable=True),
    schema='finance_meta',
    redshift_distkey=None,
    redshift_diststyle=None,
    redshift_interleaved_sortkey=None,
    redshift_sortkey=()
    )
    op.create_table('dw_meta_bridges',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('"identity"(443328, 0, \'1,1\'::text)'), autoincrement=False, nullable=False),
    sa.Column('database_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('schema_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('column_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('ordinal_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('column_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('column_default', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('is_nullable', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('character_maximum_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeric_precision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeric_scale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('is_primary_key', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auto_increment', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('foreign_key_table', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('foreign_key_column', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('unique_constraint', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dw_meta_bridges_pkey'),
    schema='finance_meta',
    redshift_distkey=None,
    redshift_diststyle=None,
    redshift_interleaved_sortkey=None,
    redshift_sortkey=()
    )
    op.drop_table('metadata_source_import_iseries_mhf', schema='finance_meta')
    op.drop_table('metadata_source_import_iseries_gl', schema='finance_meta')
    op.drop_table('metadata_source_import_iseries', schema='finance_meta')
    op.drop_table('metadata_source_import_fred', schema='finance_meta')
    op.drop_table('metadata_source_import_flat_files', schema='finance_meta')
    op.drop_table('metadata_source_import_bls', schema='finance_meta')
    op.drop_table('metadata_source_import_bea', schema='finance_meta')
    # ### end Alembic commands ###
