"""Initial Migration

Revision ID: 88c415701cd5
Revises: 
Create Date: 2024-08-18 18:11:39.199238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c415701cd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bridge_category', 'dim_category', ['child_category_key'], ['category_key'], source_schema='finance_dw', referent_schema='finance_dw')
    op.create_foreign_key(None, 'bridge_category', 'dim_category', ['category_key'], ['category_key'], source_schema='finance_dw', referent_schema='finance_dw')
    op.create_foreign_key(None, 'bridge_indirect_cash_flow_category', 'dim_indirect_cash_flow_category', ['child_indirect_cash_flow_category_key'], ['indirect_cash_flow_category_key'], source_schema='finance_dw', referent_schema='finance_dw')
    op.create_foreign_key(None, 'bridge_indirect_cash_flow_category', 'dim_indirect_cash_flow_category', ['indirect_cash_flow_category_key'], ['indirect_cash_flow_category_key'], source_schema='finance_dw', referent_schema='finance_dw')
    op.create_foreign_key(None, 'bridge_map_cash_flow', 'dim_indirect_cash_flow_category', ['indirect_cash_flow_category_key'], ['indirect_cash_flow_category_key'], source_schema='finance_dw', referent_schema='finance_dw')
    op.create_foreign_key(None, 'bridge_map_cash_flow', 'dim_account', ['gl_account_id_key'], ['gl_account_id_key'], source_schema='finance_dw', referent_schema='finance_dw')
    op.create_unique_constraint(None, 'dim_journal_description', ['description'], schema='finance_dw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dim_journal_description', schema='finance_dw', type_='unique')
    op.drop_constraint(None, 'bridge_map_cash_flow', schema='finance_dw', type_='foreignkey')
    op.drop_constraint(None, 'bridge_map_cash_flow', schema='finance_dw', type_='foreignkey')
    op.drop_constraint(None, 'bridge_indirect_cash_flow_category', schema='finance_dw', type_='foreignkey')
    op.drop_constraint(None, 'bridge_indirect_cash_flow_category', schema='finance_dw', type_='foreignkey')
    op.drop_constraint(None, 'bridge_category', schema='finance_dw', type_='foreignkey')
    op.drop_constraint(None, 'bridge_category', schema='finance_dw', type_='foreignkey')
    # ### end Alembic commands ###
