"""Added DimPartId

Revision ID: be46a8e1580e
Revises: c4dfdfa3d2e8
Create Date: 2024-09-11 16:08:01.665347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be46a8e1580e'
down_revision: Union[str, None] = 'c4dfdfa3d2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_part_id',
    sa.Column('part_id_key', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Numeric(precision=22, scale=0), nullable=True),
    sa.Column('part_id', sa.String(length=24), nullable=True),
    sa.Column('part_id_2', sa.String(length=24), nullable=True),
    sa.Column('product_line', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('part_description', sa.String(length=400), nullable=True),
    sa.Column('part_description_specific', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('subcategory', sa.String(length=60), nullable=True),
    sa.Column('segment', sa.String(length=60), nullable=True),
    sa.Column('popularity', sa.String(length=4), nullable=True),
    sa.Column('master_installer_flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('part_id_key'),
    schema='finance_dw'
    )
    op.create_table('dim_part_id_source',
    sa.Column('part_id_key', sa.Integer(), nullable=False),
    sa.Column('sku', sa.Numeric(precision=22, scale=0), nullable=True),
    sa.Column('part_id', sa.String(length=24), nullable=True),
    sa.Column('part_id_2', sa.String(length=24), nullable=True),
    sa.Column('product_line', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('part_description', sa.String(length=400), nullable=True),
    sa.Column('part_description_specific', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('subcategory', sa.String(length=60), nullable=True),
    sa.Column('segment', sa.String(length=60), nullable=True),
    sa.Column('popularity', sa.String(length=4), nullable=True),
    sa.Column('master_installer_flag', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('part_id_key'),
    schema='finance_etl'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_part_id_source', schema='finance_etl')
    op.drop_table('dim_part_id', schema='finance_dw')
    # ### end Alembic commands ###
