"""Added columns to both duration and annum dimensions.

Revision ID: c915de520d6d
Revises: 64618c04e010
Create Date: 2024-08-19 08:58:28.623172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c915de520d6d'
down_revision: Union[str, None] = '64618c04e010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_annum', sa.Column('annum_description', sa.String(length=30), nullable=True), schema='finance_dw')
    op.add_column('dim_duration', sa.Column('duration_description', sa.String(length=30), nullable=True), schema='finance_dw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_duration', 'duration_description', schema='finance_dw')
    op.drop_column('dim_annum', 'annum_description', schema='finance_dw')
    # ### end Alembic commands ###
