create or replace procedure finance_etl.sp_populate_source_table_dim_calendar()
as $$
begin
    insert into finance_etl.dim_calendar_source
    (
        date_key,
        calendar_date,
        year,
        quarter,
        month,
        name_of_day,
        day_of_month,
        day_of_year,
        week,
        day_of_week,
        holiday,
        weighted_value,
        days_in_month,
        name_of_month,
        name_of_month_abb,
        first_date_of_month,
        first_date_of_year,
        first_date_of_quarter,
        first_date_of_ltm,
        py_date,
        py_year,
        py_month,
        pm_date,
        pm_year,
        pm_month,
        fiscal_year,
        fiscal_week,
        day_of_fiscal_year,
        day_frequency_of_fiscal_year,
        first_date_of_fiscal_week,
        last_date_of_fiscal_week,
        py_fiscal_year,
        cs_py_daily_date,
        cs_py_daily_fiscal_year,
        cs_py_daily_fiscal_week,
        first_date_of_cs_py_fiscal_week,
        weighted_business_days_mtd,
        weighted_business_days_qtd,
        weighted_business_days_ytd,
        weighted_business_days_ltm,
        weighted_business_days_wtd,
        active
    )

    select
    -1 as date_key,
    cast(null as date) as calendar_date,
    0 as year,
    0 as quarter,
    0 as month,
    'None' as name_of_day,
    0 as day_of_month,
    0 as day_of_year,
    0 as week,
    0 as day_of_week,
    'None' as holiday,
    0 as weighted_value,
    0 as days_in_month,
    cast('None' as char(9)) as name_of_month,
    cast('None' as char(3)) as name_of_month_abb,
    cast('2999-12-31' as date) as first_date_of_month,
    cast('2999-12-31' as date) as first_date_of_year,
    cast('2999-12-31' as date) as first_date_of_quarter,
    cast('2999-12-31' as date) as first_date_of_ltm,
    cast('2999-12-31' as date) as py_date,
    0 as py_year,
    0 as py_month,
    cast('2999-12-31' as date) as pm_date,
    0 as pm_year,
    0 as pm_month,
    0 as fiscal_year,
    0 as fiscal_week,
    0 as day_of_fiscal_year,
    0 as day_frequency_of_fiscal_year,
    cast('2999-12-31' as date) as first_date_of_fiscal_week,
    cast('2999-12-31' as date) as last_date_of_fiscal_week,
    0 as py_fiscal_year,
    cast('2999-12-31' as date) as cs_py_daily_date,
    0 as cs_py_daily_fiscal_year,
    0 as cs_py_daily_fiscal_week,
    cast('2999-12-31' as date) as first_date_of_cs_py_fiscal_week,
    0 as weighted_business_days_mtd,
    0 as weighted_business_days_qtd,
    0 as weighted_business_days_ytd,
    0 as weighted_business_days_ltm,
    0 as weighted_business_days_wtd,
    0 as active

    union all

    select
    cast(replace(calendar_date, '-', '') as int) as date_key,
    calendar_date,
    year,
    quarter,
    month,
    name_of_day,
    day_of_month,
    day_of_year,
    week,
    day_of_week,
    holiday,
    weighted_value,
    days_in_month,
    name_of_month,
    name_of_month_abb,
    first_date_of_month,
    first_date_of_year,
    first_date_of_quarter,
    first_date_of_ltm,
    py_date,
    py_year,
    py_month,
    pm_date,
    pm_year,
    pm_month,
    fiscal_year,
    fiscal_week,
    day_of_fiscal_year,
    day_frequency_of_fiscal_year,
    first_date_of_fiscal_week,
    last_date_of_fiscal_week,
    py_fiscal_year,
    cs_py_daily_date,
    cs_py_daily_fiscal_year,
    cs_py_daily_fiscal_week,
    first_date_of_cs_py_fiscal_week,
    weighted_business_days_mtd,
    weighted_business_days_qtd,
    weighted_business_days_ytd,
    weighted_business_days_ltm,
    weighted_business_days_wtd,
    1 as active
    from finance_staging.flat_file_calendar
;

end;
$$ language plpgsql;
